language: emacs-lisp
sudo: required
dist: trusty
# FIXME Disable caching https://github.com/flycheck/emacs-travis/issues/22
# cache:
#   - directories:
#       - "$HOME/emacs/"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.3
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - ls *
  - cask --version
  - make
