language: emacs-lisp
sudo: required
dist: trusty
# Disable caching https://github.com/flycheck/emacs-travis/issues/22
# cache:
#   - directories:
#       - "$HOME/emacs/"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  # - EMACS_VERSION=24.3
  # - EMACS_VERSION=25.1-rc2
  # - EMACS_VERSION=26.0.91 PRETEST=yes
  # - EMACS_VERSION=25.3
  # - EMACS_VERSION=26.3
  - EMACS_VERSION=26.3
  # - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - ls *
  - cask --version
  - cask exec emacs -Q -batch -L . -l test/ess-r-spreadsheet-tests.el -f ert-run-tests-batch-and-exit
